page_icon: 'src\view\images\sunmatch-icon.ico'
df_city_states: 'src\model\db\city-states.xlsx'

cadastro:
  page_title: 'SunMatch | Cadastro de instaladores' 
  
home:
  page_title: 'SunMatch'
  header_image: 'src\view\images\sunmatch-logo-horizon_slim.png'
  href_btn_anuncios: 'http://localhost:8501/Anúncios'
  href_btn_cadastro: 'http://localhost:8501/Cadastro'
